### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by licaoyu** [DHI-GRAS/qgis-python-fmask#3]
Hi，there
   I am a postgraduate student in China and I study in Remote Sensing.And I get job in python pluign development on QGIS.The plugin mainly does the job about the processing of remote sensing imagery.When I search for the code and I find your project here,it is very useful and helpful .But I get trouble in moving this in QGIS because I am new in this. Could you please show me some details of how to develop this plugin in QGIS? You can reply me here and you can also send me  an email with 'caoyuli@whu.edu.cn'.
   Very thankful for reading this.
Good Day!

**Comment by j08lue** [comment]
Thanks for your interest. So if I get this right, you want to make an Fmask Plugin for QGIS? What is the added benefit compared to the scripts we have here?

The reason why we chose scripts over plugin is that they are much easier to write and maintain. We bascially only wanted a thin interface to the somewhat clumsy Python Fmask command-line interface and data preparation steps, so we easily can run them from QGIS and get some basic integration.

You are very welcome to take the code or approach from this repo and turn it into a plugin, but I am afraid we cannot help with that. Please let us know if you succeed, though, then we can refer to your plugin.

**Comment by j08lue** [comment]
Stale.
